package org.codehaus.groovy.modules.scriptom.test

import groovy.util.GroovyTestCase

import org.codehaus.groovy.scriptom.*

/**
 * Sets up test to load Jacob.  Assumes process per test.  This sets up the Jacob DLL using a trick.
 * The jacob-dll-path.properties file is generated by the build early in the lifecycle.  On each test,
 * the JNI library is loaded by Jacob.  
 * @author Jason Smith
 */
abstract class BaseJacobTest extends GroovyTestCase
{
    public void setUp() 
	{
    	Properties properties = new Properties()
    	properties.load(getClass().getClassLoader().getResourceAsStream('jacob-dll-path.properties'))
    	System.setProperty('jacob.dll.path', properties.getProperty('jacob.dll.path'))
    }	
}
